version: "3.5"
services:
    postgres:
        container_name: postgres
        image: "postgres:latest"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes: 
            - /home/vane/Documentos/Proyectos/Nestjs/BaseDeDatos/Postgres/tasks-bd:/var/lib/postgresql/data
    tasks:
        container_name: tasks
        depends_on: 
            - postgres
        build: 
            context: ./tasks
            dockerfile: Dockerfile.dev
        volumes: 
            - ./tasks:/app
            - /app/node_modules
        ports: 
            - "3000:3000"
